/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xiao lin
 */
public class HistoryJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HistoryJFrame
     */
    public HistoryJFrame(String an) throws SQLException {
        initComponents();
        printTable(an);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historytable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        historytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(historytable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTable historytable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   

    private void printTable(String an) throws SQLException {
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/banking", "root", "root");    //connect database
        String sql = "SELECT * FROM HISTORY WHERE ACCOUNTNUMBER='"+an+"'";
         ResultSet rs = con.prepareStatement(sql).executeQuery();
         
         Vector columnName = new Vector();//Vector to put column name
         columnName.addElement("Transaction Type");//set column name
         columnName.addElement("Transaction Amount");
         columnName.addElement("Transaction Time");
         columnName.addElement("Previous Amount");
         columnName.addElement("After Amount");
         
         Vector rows = new Vector();
         while(rs.next()){
            Vector newrow = new Vector();
            newrow.addElement(rs.getString("TYPE"));
            newrow.addElement(rs.getDouble("AMOUNT"));
            newrow.addElement(rs.getTimestamp("TIME"));
            newrow.addElement(rs.getDouble("PREVIOUSAMOUNT"));
            newrow.addElement(rs.getDouble("AFTERAMOUNT"));
            rows.addElement(newrow);
         }
         DefaultTableModel datamodel = new DefaultTableModel(rows,columnName);
         historytable.setModel(datamodel);
    }
}
